allowBuilds:
  "esbuild": false
  "sharp": false

catalog:
  "typescript": "^7.0.2"
  "unplugin-unused": "0.6.0"
  "vite": "8.2.0"

overrides:
  "tinybench": "https://registry.npmjs.org/tinybench/-/tinybench-5.1.0.tgz"
  "typescript": "catalog:"
  "unplugin-unused": "catalog:"
  "vitest>vite": "catalog:"
  "@vitest/mocker>vite": "catalog:"

patchedDependencies:
  "starlight-theme-rapide": "patches/starlight-theme-rapide.patch"
