/**
 * This file contains various packed constants used by the decoder.
 */
import type { IntRange, TupleOf } from "type-fest";

/**
 * Unpack string to an array of integer constants.
 * @param n Width (number of characters) of each packed entry.
 * @param s String to unpack.
 * @returns Unpacked integer constants.
 */
const parseWidth = (n: number, s: string): number[] | undefined =>
  s.match(new RegExp(`.{${n}}`, "g"))?.map((x) => parseInt(x, 36));

/**
 * Critical frequencies for audio bands.
 */
export const AUDIO_CRITICAL_FREQS = parseWidth(
  3,
  "02s05k08c0b40e60hi0le0pk0u00za1541bs1jk1sg2302fi2us3e84384xs5xw7bw99cbyk",
) as TupleOf<24, number>;

/**
 *  Run-lengths permitted for compression of audio with RLE.
 */
export const AUDIO_RLE_LENGTH_TABLE = parseWidth(2, "0g0o0w141c1s20282g2o2w343c3k74e8") as TupleOf<
  16,
  number
>;

/**
 * Run-lengths permitted for compression of video with RLE.
 */
export const RLE_LENGTHS = [4, 8, 12, 32] as const;

export const BIK_TREE_CODES = parseWidth(
  2,
  "000102030405060708090a0b0c0d0e0f0001030507090b0d0f0j0l0n0p0r0t0v00020109050l0d0t030j0b0r070n0f0v0002060109050d0t030j0b0r070n0f0v000402060109050d030j0b0r070n0f0v0004020a060e0109050d030b070n0f0v00020a060e0109050d030b0r070n0f0v000105030j0b0r1n07130n1j0f1b0v1r0001030j0b170r1n07130n1j0f1b0v1r0001050d030j0b0r07130n1j0f1b0v1r000201050d030j0b0r070n1j0f1b0v1r000109050d030j0b0r070n1j0f1b0v1r000201030j0b0r1n07130n1j0f1b0v1r0001050307130n1j0f271b330v2n1r3j00010503070n1j3b0f271b330v2n1r3j000201050307130n1j0f1b330v2n1r3j",
) as TupleOf<256, IntRange<0, 256>>;

export const BIK_TREE_LENS = parseWidth(
  1,
  "4444444444444444145555555555555522445555555555552334445555555555333344445555555533444444444455552444444444555555133555666666666612556666666666661344555566666666223445555566666614444555556666662225556666666666133366667777777713335677777777772233366666777777",
) as TupleOf<256, IntRange<1, 8>>;

/**
 * DCT scan order for 8x8 blocks.
 */
export const BIK_SCAN = parseWidth(
  2,
  "0001080902030a0b04050c0d06070e0f0k0l0s0t0m0n0u0v0g0h0o0p0w0x14150y0z16171c1d1k1l1e1f1m1n0i0j0q0r1011181912131a1b1g1h1o1p1i1j1q1r",
) as TupleOf<64, IntRange<0, 64>>;

export const BIK_PATTERNS = parseWidth(
  2,
  "00080g0o0w141c1k1l1d150x0p0h0901020a0i0q0y161e1m1n1f170z0r0j0b03040c0k0s10181g1o1p1h19110t0l0d05060e0m0u121a1i1q1r1j1b130v0n0f071n1m1l1k1c1d1e1f171615140w0x0y0z0r0q0p0o0g0h0i0j0b0a090800010203040506070f0e0d0c0k0l0m0n0v0u0t0s101112131b1a19181g1h1i1j1r1q1p1o0p0h0i0q0r0j0b03020a090100080g0o0w141c1k1l1d15161e1m1n1f170z0y0x0t0l0m0u0v0n0f07060e0d05040c0k0s10181g1o1p1h191a1i1q1r1j1b131211030b020a010900080g0o0h0p0i0q0j0r0z170y160x150w141c1k1d1l1e1m1f1n1o1g1p1h1q1i1r1j1b131a12191118100s0k0t0l0u0m0v0n0f070e060d050c040o0p0g0h0809000102030a0b0i0j0q0r0s0t0k0l0c0d040506070e0f0m0n0u0v13121b1a1j1i1r1q1p1o1h1g191811100z0y17161f1e1n1m1l1k1d1c15140x0w0001020308090a0b0g0h0i0j0o0p0q0r0w0x0y0z141516171c1d1e1f1k1l1m1n040506070c0d0e0f0k0l0m0n0s0t0u0v1011121318191a1b1g1h1i1j1o1p1q1r06070f0e0d050c04030b020a090100080g0o0h0p0i0q0j0r0k0s0l0t0m0u0n0v131b121a111910180z170y160x150w141d1c1k1l1m1e1n1f1o1g1p1h1i1j1r1q00010203040506070f0e0d0c0b0a09080g0h0i0j0k0l0m0n0v0u0t0s0r0q0p0o0w0x0y0z101112131b1a1918171615141c1d1e1f1g1h1i1j1r1q1p1o1n1m1l1k0008090102030b0a0i0j0r0q0p0h0g0o0w14150x0y0z17161e1d1c1k1l1m1n1f1g1o1p1q1r1j1i1h19181011121a1b130v0n0m0u0t0s0k0l0d0c0405060e0f070o0p0g0h0809000102030a0b0i0j0q0r0s0t0k0l0c0d040506070e0f0m0n0u0v12131a1b1i1j1q1r1o1p1g1h181910110y0z16171e1f1m1n1k1l1c1d14150w0x00080109020a030b0j0r0i0q0h0p0g0o0w140x150y160z171f1n1e1m1d1l1c1k1o1g1p1h1q1i1r1j1b131a12191118100v0n0u0m0t0l0s0k0c040d050e060f0700080g0o0p0q0r0j0b030201090h0i0a040c0k0s0t0u0v0n0f0706050d0l0m0e10181g1o1p1q1r1j1b131211191h1i1a0w141c1k1l1m1n1f170z0y0x151d1e160008090102030b0a0j0r0q0i0h0g0o0p0x0w1415160y0z171f1n1m1e1d1l1k1c1g1o1p1h1i1q1r1j1b13121a191810110t0s0k0l0m0u0v0n0e0f0706050d0c040o0g08000102030b0j0r0q0p0h0a090i0s0k0c040506070f0n0v0u0t0l0e0d0m1o1g18101112131b1j1r1q1p1h1a191i1k1c140w0x0y0z171f1n1m1l1d16151e00080901020a0i0h0g0o0p0q0r0j0b0307060e0f0n0m0l0d05040c0k0s0t0u0v1r1q1i1j1b1a191h1p1o1g18101112131k1c1d1l1m1e1615140w0x0y0z171f1n000108090g0h0o0p0w0x14151c1d1k1l1m1n1e1f16170y0z0q0r0i0j0a0b020304050c0d0k0l0s0t101118191g1h1o1p1q1r1i1j1a1b12130u0v0m0n0e0f0607",
) as readonly IntRange<0, 64>[];

/**
 * (I)DCT coefficient quantization table
 * -------------------------------------
 *
 * Table contains a sub-table for intra-frame followed by a sub-table for inter-frame values.
 * Each sub-table consists of 16 levels, each containing 64 values for an 8x8 DCT block. Each
 * level is generated by scaling a base quantization matrix by a predetermined factor.
 */

/**
 * Base quantization matrix for intra/inter-frame coded blocks.
 */
const BASE_QUANT = parseWidth(
  4,
  "1ekg1y512ofx3prp1u2j1ylz44x23fpo1ekg1b6i35z623rv11mo0j6m1g700wnm2zd42m373ict2r9z1st50x1f1wdt0tqg33hr4an92sca3v6e2jnk3j4m27gn2rvu33hr2sca2m3732yg1nv62mwc14401jmw2he428g81u2u1lf33wa03i8w3n3p35ma38xs2cff2jvm1wab1m5l0rwj1b1b0nal1szw1f2g1ctx1b9t18fl0mnh0wk80jyv1ekg22iu2bah37j01y771uw736jw2v3e1kw018p42foa1wvw0why0gkg1bg60ped2ept1zdl2dh51v5p1d5z0p2c1a9c0nkz2ept3ca329rd35ej20ow2stq1nlh2anv2mz52dh525v720zx16re1s210oey0xv51oc81iay0y6g0urd35av2tyv2yto2o5023uo1nlh1sk91eq6151u0lss0yxw0ht91a6k10a90q5r0l8l0px30d7p0emo07xt",
) as readonly number[];

/**
 * Scaling factors for each of the quantization levels.
 */
const QUANT_FACTORS = [
  1.0,
  4 / 3,
  5 / 3,
  2.0,
  8 / 3,
  7 / 2,
  4.0,
  5.0,
  6.0,
  8.0,
  12.0,
  17.0,
  22.0,
  28.0,
  34.0,
  44.0,
];

/**
 * Generate quantization tables by scaling a base matrix.
 *
 * @param baseMatrix - The base quantization matrix (64 values)
 * @returns Flat array of 1024 values (16 tables x 64 coefficients)
 */
function generateQuantTables(baseMatrix: readonly number[]): number[] {
  const tables: number[] = [];

  for (let level = 0; level < 32; level++) {
    const factor = QUANT_FACTORS[level % 16];
    const subTableOffset = level > 15 ? 64 : 0;

    for (let i = 0; i < 64; i++) {
      // Scale the base quantization value and round to nearest integer
      tables.push(Math.round((baseMatrix[i + subTableOffset] as number) * (factor as number)));
    }
  }

  return tables;
}

/**
 * Generate the intra/inter-frame block quantization tables.
 *
 * Used for quantizing DCT coefficients in intra-frame coded blocks (I-frames) and
 * inter-frame coded blocks (P-frames).
 */
export const BIK_QUANT: number[] = generateQuantTables(BASE_QUANT);
